evenements = {
    "Crise pétrolière (1973)":"La crise pétrolière de 1973 a été déclenchée par l'embargo pétrolier de l'OPEP, provoquant une augmentation spectaculaire des prix du pétrole. Cela a eu des répercussions économiques mondiales, y compris en Suisse, qui dépend fortement des importations d'énergie. La crise a incité de nombreux pays, y compris la Suisse, à explorer des alternatives énergétiques et à renforcer leur efficacité énergétique.",
    "Chute du mur de Berlin (1989)":"La chute du mur de Berlin a marqué la fin de la Guerre froide et le début de l'unification allemande. Cela a eu des répercussions sur l'Europe et a contribué à une période de changement politique. En Suisse, cela a renforcé l'idée de la fin de la neutralité stricte, conduisant à une participation accrue dans les organisations internationales.",
    "Attentats du 11 septembre 2001":"Les attentats du 11 septembre ont profondément affecté la sécurité mondiale et ont conduit à des changements dans les politiques internationales. En Suisse, cela a influencé les politiques de sécurité et a conduit à une coopération renforcée avec d'autres nations pour lutter contre le terrorisme.",
    "Adhésion à l'ONU (2002)": "En 2002, la Suisse a rejoint les Nations Unies, marquant un changement significatif dans sa politique étrangère. Cela a eu des répercussions sur la diplomatie suisse et a influencé les relations internationales du pays.",
    "Crise financière mondiale (2008)": "La crise financière mondiale de 2008 a eu des répercussions sur l'économie suisse. Le gouvernement suisse a pris des mesures pour atténuer les effets de la crise, ce qui a également influencé les débats politiques sur la régulation financière et la stabilité économique.",
    "Crise de l'amiante (années 1980)": "La crise de l'amiante dans les années 1980 a conduit à des réformes majeures en matière de santé et de sécurité au travail en Suisse. Les discussions politiques ont porté sur la réglementation de l'industrie et la protection des travailleurs, influençant ainsi la législation du travail.",
    "Printemps arabe (2010-2012)":" Les soulèvements populaires dans plusieurs pays du monde arabe ont entraîné des changements politiques et sociaux significatifs. La Suisse, en tant qu'acteur diplomatique, a suivi de près ces événements et a adapté sa politique étrangère en conséquence.",
    "Crise migratoire en Europe (2015)": "La crise migratoire en Europe en 2015 a eu des répercussions en Suisse, suscitant des discussions sur la politique d'asile, l'intégration des migrants et la solidarité européenne. Ces questions ont continué à être des thèmes majeurs dans le paysage politique suisse."
}